# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79ec8b7aa36e165488ffb33e9fe53211bfc84b893bb4d1b58631dd71ea2689542b6962e894a458beac5c2aafe324f0765168823bd1e3c2e5f8026db1ccdc94fb

test:
  secret_key_base: 5cef3f9c04257bc3eaab0ebb29eb17297a1a9816d71d964d7f6625c6926beeedfb7844a18a12418e53ab42ed589f053d3b4c52b713723c2143c99c59360f5fa5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
